language: cpp

compiler:
  - clang
  - gcc

env:
  - MPI=mpich2
  - MPI=openmpi

matrix:
  exclude:
    - env: MPI=mpich2
      compiler: clang

notifications:
  email: false

install:
  - sudo add-apt-repository -y ppa:staticfloat/julia-deps
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - echo deb http://llvm.org/apt/precise/ llvm-toolchain-precise main | sudo tee -a /etc/apt/sources.list
  - curl http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y lcov clang-3.7 gcc-4.9 g++-4.9 gfortran-4.9 libstdc++-4.9-dev libopenblas-dev liblapack-dev
  - git pull --recurse-submodules
  - sh travis/install-mpi.sh $MPI
  - sudo pip install cpp-coveralls
  - curl http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
  - curl http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz | tar xz
  - sudo make -j8 -l8 -C lcov-1.11/ install
  - gem install coveralls-lcov

before_script:
  - if test x$CC = xclang; then;
      export CC=clang-3.7;
      export CXX=clang++-3.7;
      export FLAGS="-O3 -Wall -Wl,--no-keep-memory";
    fi
  - if test x$CC = xgcc; then;
      export CC=gcc-4.9;
      export CXX=g++-4.9;
      export FLAGS="-g -Os -Wall -fprofile-arcs -ftest-coverage";
    fi
  - sudo hostname localhost
  - test $MPI == mpich2 && MPIEXEC='mpiexec -launcher fork' || true
  - lcov --directory . --zerocounters

script:
  - mkdir build && cd build;
  - cmake .. -DASSERT=ON -DASSERT2=ON -DEL_TESTS=ON -DEL_EXAMPLES=ON -DCXX_FLAGS="$FLAGS" -DC_FLAGS="$FLAGS" -DFortran_FLAGS="$FLAGS" -DCMAKE_BUILD_TYPE=Release;
    if test $? -ne 0; then cat CMakeFiles/CMakeError.log; fi
  - make -j3 && sudo make -j2 install && sudo ctest -j3 --output-on-failure

after_success:
  - if test x$CC = xgcc-4.9; then;
       lcov --directory . --capture --output-file coverage.info;
       lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info;
       lcov --list coverage.info;
       coveralls-lcov --repo-token orrZO32nywoXo9Y70QEcCJ3M8v00QVOaC coverage.info;
    fi

